version: '3.1'

services:

  db:
    image: postgres:15beta2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: demo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080